sudo: required
services:
    - docker

before_install:
    - docker build -t satsingh/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true satsingh/react-test npm test

after_success:
    - docker build -t satsingh/multi-client ./client
    - docker build -t satsingh/multi-nginx ./nginx
    - docker build -t satsingh/multi-server ./server
    - docker build -t satsingh/multi-worker ./worker
    # push to dockerhub once logged in
    - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
    - docker push satsingh/multi-client
    - docker push satsingh/multi-nginx
    - docker push satsingh/multi-server
    - docker push satsingh/multi-worker